package com.pdl.blog.dao;

import com.pdl.blog.pojo.Articles;
import com.pdl.blog.pojo.ArticlesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface ArticlesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    long countByExample(ArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    int deleteByExample(ArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    int insert(Articles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    int insertSelective(Articles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    List<Articles> selectByExample(ArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    Articles selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    int updateByExampleSelective(@Param("record") Articles record, @Param("example") ArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    int updateByExample(@Param("record") Articles record, @Param("example") ArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    int updateByPrimaryKeySelective(Articles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    int updateByPrimaryKey(Articles record);

    @Select("SELECT id,create_date,title,cid FROM articles ORDER BY id DESC LIMIT 5")
    List<Articles> getLastList();

    @Select("SELECT id,create_date,title,cid FROM articles ORDER BY id DESC")
    List<Articles> getList();
    @Select("SELECT id,create_date,title,cid FROM articles WHERE cid = #{cid} ORDER BY id DESC")
    List<Articles> getListByCid(int cid);
}