package com.pdl.blog.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Articles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.id
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.title
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.create_date
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.update_date
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.M_content
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    private String mContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.H_content
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    private String hContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.uid
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.cid
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    private Integer cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.id
     *
     * @return the value of articles.id
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.id
     *
     * @param id the value for articles.id
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.title
     *
     * @return the value of articles.title
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.title
     *
     * @param title the value for articles.title
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.create_date
     *
     * @return the value of articles.create_date
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.create_date
     *
     * @param createDate the value for articles.create_date
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.update_date
     *
     * @return the value of articles.update_date
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.update_date
     *
     * @param updateDate the value for articles.update_date
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.M_content
     *
     * @return the value of articles.M_content
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    public String getmContent() {
        return mContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.M_content
     *
     * @param mContent the value for articles.M_content
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    public void setmContent(String mContent) {
        this.mContent = mContent == null ? null : mContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.H_content
     *
     * @return the value of articles.H_content
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    public String gethContent() {
        return hContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.H_content
     *
     * @param hContent the value for articles.H_content
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    public void sethContent(String hContent) {
        this.hContent = hContent == null ? null : hContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.uid
     *
     * @return the value of articles.uid
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.uid
     *
     * @param uid the value for articles.uid
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.cid
     *
     * @return the value of articles.cid
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.cid
     *
     * @param cid the value for articles.cid
     *
     * @mbg.generated Sat Jan 19 13:56:32 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }
}