package com.pdl.blog.pojo;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.id
     *
     * @mbg.generated Fri Dec 28 23:48:14 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category
     *
     * @mbg.generated Fri Dec 28 23:48:14 CST 2018
     */
    private String category;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.id
     *
     * @return the value of category.id
     *
     * @mbg.generated Fri Dec 28 23:48:14 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.id
     *
     * @param id the value for category.id
     *
     * @mbg.generated Fri Dec 28 23:48:14 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category
     *
     * @return the value of category.category
     *
     * @mbg.generated Fri Dec 28 23:48:14 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category
     *
     * @param category the value for category.category
     *
     * @mbg.generated Fri Dec 28 23:48:14 CST 2018
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }
}